### PR TITLE
Added import of json

### PR DESCRIPTION
**Pull request by pmansvelder**
Hello Michel, 
I came across this trying to control my Naim Uniti Atom with my domotics system (Home Assistant), and it works really good, thank you for sharing this! I would like to try to elaborate on this to make it a fully functional integation within Home Assistant, can I ask if you know if there is any source information about the protocols NAIM uses?

### CODE REVIEW

**Comment by pepitooo** [comment]
Hello Peter,

I would say yes, you can have access to all informations you have on the Naim mobile app (ios, android) but I never need it. 
Some information are simple to get, some other more difficult, 
It can be a good idea to do a plugin for HA.
I'm using HA, but I control it via roon plugin.

If you tell me exactly what information you really need I can have a look.

**Comment by pmansvelder** [comment]
Hello Michel,

I used your scripts to get some information (volume, mute status), and to switch the Naim on or off and select an input.
What I couldn’t find was the information on what input is currently selected; when I use the URL http://uniti-atom:15081/inputs I see the inputs, but not which one is currently selected.
Could you help me with this?

As regards to the plugin, I will start an enquiry on the forum, since I have no idea how to start.
—

Peter Mansvelder
Maker | Domotica | IT
***@***.***

**Comment by pepitooo** [comment]
I will have a look to get the selected source tonight.

**Comment by pepitooo** [comment]
Hello Peter,

By calling `http://uniti-atom:15081/nowplaying`
you will get a json with the source selected plus other information.
```
{
  "version": "1.4.0",
  "changestamp": "0",
  "name": "Now Playing",
  "ussi": "nowplaying",
  "class": "object.nowplaying",
  "audioPresent": "0",
  "canResume": "0",
  "cpu": "287",
  "error": "0",
  "live": "1",
  "mimeType": "audio/x-wav",
  "repeat": "0",
  "restrictPause": "0",
  "restrictPeekNext": "0",
  "restrictPeekPrev": "0",
  "restrictResume": "0",
  "restrictSeek": "0",
  "restrictSkipNext": "0",
  "restrictSkipPrev": "0",
  "restrictStop": "0",
  "shuffle": "0",
  "source": "inputs/dig2",
  "sourceMultiroom": "inputs/none",
  "streamDomain": "",
  "streamMessage": "",
  "transportPosition": "276157",
  "transportState": "2"
}
```
In my case here `inputs/dig2`

Then you can call /inputs to get the alias name

One other important call is `http://uniti-atom:15081/notify` for what you want to do
it's a stream with events
 - track position
 - track change
 - track atwork
 - volume
 - source change
 - ...

```
id:350119
event:nowplaying
data:{"version":"1","ussi":"nowplaying","id":"1","parameters":{"transportPosition":"64000"}}

id:350120
event:levels
data:{"version":"1","ussi":"levels","id":"0","parameters":{"volume":"22"}}

id:350121
event:levels
data:{"version":"1","ussi":"levels\/room","id":"0","parameters":{"volume":"22"}}

id:350122
event:userinterface
data:{"version":"1","ussi":"userinterface","id":"0","parameters":{"lightActive":"1"}}

id:350123
event:nowplaying
data:{"version":"1","ussi":"nowplaying","id":"1","parameters":{"transportPosition":"65000"}}

id:350124
event:levels
data:{"version":"1","ussi":"levels","id":"0","parameters":{"volume":"10"}}

id:350125
event:levels
data:{"version":"1","ussi":"levels\/room","id":"0","parameters":{"volume":"10"}}
```

With this you should be able to modify a home assistant media player plugin for Naim

**Pull request closed without merging**
